### ISSUE TITLE
subset operation

### ISSUE THREAD

**Issue by averagehat** [marianobarrios/dregex#1]
I'd like to use this library to find the subset of two regexes. That seems possible using the given operations if you interprest `".*"` as the universal set.

An empty set would be one which does not intersect with the universal set (`".*"`).
If (A - B) is empty, then A is a subset of B. 

if (B - A) is non-empty,  but (A - B) is empty, then A is a proper subset of B.
```scala
// U is defined as .* earlier
isSubset = !(A.diff(B).doIntersect(U))
isProperSubset = (B.diff(A).doIntersect(U) && !(A.diff(B).doIntersect(U)))
```

Do you see any holes in this? If you can okay it, I'll make a pull request for it.

**Comment by marianobarrios** [comment]
Hi Mike,

Thanks for your interest.
I don't see any holes. Note that the Regex trait has a method called
matchesAnything(), that would simplify the detection of "empty" regular
expressions.
I am looking forward to your request. Please include at least some test. :-)

Thanks again and regards.

**Comment by marianobarrios** [comment]
#2
