### ISSUE TITLE
Case-insensitive matching doesn't work with digits

### ISSUE THREAD

**Issue by donnerpeter** [marianobarrios/dregex#102]
`Regex.compile("\\d", Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CASE).matches("3")` yields `false` :(

**Comment by donnerpeter** [comment]
With letters as well: both of these yield false:
`Regex.compile("[ab]", Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CASE).matches("a")`
`Regex.compile("foo|bar", Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CASE).matches("foo")`

But this is true:
`Regex.compile("foo", Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CASE).matches("foo")`

**Comment by marianobarrios** [comment]
I confirm the issue (it seems like it got introduced in a refactoring some time ago...).

**Comment by marianobarrios** [comment]
Should be fixed in latest release 0.9.9
