### ISSUE TITLE
give CompiledRegex a toString method?

### ISSUE THREAD

**Issue by averagehat** [marianobarrios/dregex#3]
The build in scala regex has a nice toString method, e.g.:
```scala
scala> "foo.*\\.bar".r.toString
res4: String = foo.*\.bar
```

It would be convenient to have CompiledRegex report the same thing. This would require CompiledRegex to hold onto its initial representation but I don't think that's a bad thing. 

Right now I am having to either hold on to the original string as well or repeatedly compile the regex when I need it because I need the string representation as well.

**Comment by marianobarrios** [comment]
Yes, totally.
I could add it myself, when I have some time. 
Of course, I'd accept a pull request, if you prefer.
