### ISSUE TITLE
Getting values from JSON string

### ISSUE THREAD

**Issue by theunreal** [marianobarrios/dregex#5]
Hi,
My regex look like this to find the value of the `version` property inside a JSON;

`"version":\s*(\d+)(\.\d)?`

Using Java Pattern, I used to have something like this:

```
		Matcher matcher = patternToSearch.matcher(receiveData);
		if (matcher.find()) {
			return  matcher.group(1);
		}
```

Using this library, I couldn't find any method/example to extract the group.
using Java.pattern I could do matcher.group(1) to get the string.

Any idea?

**Comment by marianobarrios** [comment]
It's not possible. It's a fundamental limitation of the method used to represent the Regex (DFA), sadly.
