### ISSUE TITLE
Backreference send the compilation in a infinite loop

### ISSUE THREAD

**Issue by fbacchella** [marianobarrios/dregex#54]
When trying to compile `\b(\w+)(\s+\1)+\b`, dregex hangs and goes in a wild loop. I know it’s invalid as it contains a back reference. But it’s a kind of DOS, it should reject it, not hang.

**Comment by marianobarrios** [comment]
Hi Fabrice, thanks for the report. I tested that expression using the latest version (0.7.0) and could not reproduce the problem. Which version are you using?

**Comment by fbacchella** [comment]
It fails on Java 1.8.0_361. Pass on 9.0.4.
With the following code:

```
import dregex.Regex;

public class Dregex {
    public static void main (String[] args){
        String pattern = "\\b(\\w+)(\\s+\\1)+\\b";
        System.err.println(pattern);
        System.err.println(Regex.compile(pattern));
    }
}
```

**Comment by fbacchella** [comment]
For your information, I plan to test performance of your lib against some common java rexeg libraries : https://github.com/fbacchella/RegexPerf/commit/21bd45d6321bb5496d9cf2fba70b60c180850195

**Comment by marianobarrios** [comment]
Hi Fabrice. Unfortunately, I am still unable to reproduce the problem. I created a pull request that adds your regular expression: https://github.com/marianobarrios/dregex/pull/56. I seems to pass with Java 8...
